name: Build and Push Docker Image
on: workflow_dispatch
jobs:
    build-and-push-docker-image:
        runs-on: ubuntu-latest
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
            - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch
            - name: Login to dockerhub
              shell: bash
              working-directory: ./cicd-workflows
              env:
                CURRENT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
              run: ./build-and-push-docker-images.sh
