name: Build and Push to PYPI
on:
  push:
    tags:
      - 'v**'
      - '!v**-alpha'
jobs:
    Build-and-Push-to-PYPI:
        runs-on: ubuntu-latest
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
            - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch
            - name: Extract tag name
              shell: bash
              run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
              id: extract_tag
            - name: Install Poetry
              env:
                POETRY_VERSION: "1.1.12"
              uses: snok/install-poetry@v1
            - name: Build and push packages to PYPI
              shell: bash
              working-directory: ./code
              env:
                PYPI_TOKEN: ${{ secrets.PYPI }}
                PYPI_TEST_TOKEN: ${{ secrets.PYPI_TEST }}
                CURRENT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
                CURRENT_TAG: ${{ steps.extract_tag.outputs.tag }}
              run: ../cicd-workflows/build-and-push-pypi.sh
