name: Static testing
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  static-testing:
    runs-on: ubuntu-latest
    steps:
        - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Install Poetry
          uses: snok/install-poetry@v1
          with:
            version: 1.1.12
        - name: Install package
          shell: bash
          working-directory: ./code
          run: poetry install
        - name: Run Black8 formatting
          shell: bash
          working-directory: ./code
          run: poetry run black --color --diff --check .
        - name: Run flake8 linting
          shell: bash
          working-directory: ./code
          run: poetry run flake8
